#!/usr/bin/env bash

# This script sets ROS related environment variables by sourcing the setup.bash
# scripts generated by ROS on install and setup.
#
# source this file from your ~/.profile if you want to setup this workspace on login.
#
#    source <path to ADEPT repo>/tools/initWorkspace.sh
#

# Get dir where this script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE=$(dirname $DIR)

source /opt/ros/kinetic/setup.bash
source $WORKSPACE/devel/setup.bash
